---
title: Research
page-layout: article
---

## Working papers

- Atsushi Nitanda, **Dake Bu**, Yueming Lyu, Tanya Veeravalli. *Slowly Annealed Langevin Dynamics: Theory and Applications to Training-Free Guided Generation.* [[arXiv](https://arxiv.org/pdf/2605.07950)] [[code](https://github.com/anitan0925/sald/tree/main)]

- **ASPBE: Automatic State Preparation and Block Encoding for Quantum Computing.** [[GitHub](https://github.com/DakeBU/Quantum-Computing-Block-Encoding)] [arXiv under Prepare]

- **Auto-Sampling-Theory-In-Sleep: A Hierarchical Automated Theorem Proving System for Sampling Theory.** [[GitHub](https://github.com/DakeBU/Auto-Sampling-Theory-In-Sleep)] [arXiv under Prepare]

- **ABRL: A Target-Faithful Autoformalization Harness and Lean 4 Library for Bandit and Reinforcement Learning Theory.** [[GitHub](https://github.com/DakeBU/Auto-Bandit-RL-Proof-In-Sleep/)] [arXiv under Prepare]

## Publications

- **Dake Bu**, Wei Huang, Andi Han, Hau-San Wong, Qingfu Zhang, Taiji Suzuki, and Atsushi Nitanda. DPRM: A Plug-in Doob h transform-induced Token-Ordering Module for Diffusion Language Models. (ICML 2026 FoGen **Oral**) [[arXiv](https://arxiv.org/abs/2604.24357)] [[code](https://github.com/DakeBU/DPRM-DLLM)]

- **Dake Bu**, Wei Huang, Andi Han, Atsushi Nitanda, Bo Xue, Qingfu Zhang, Hau-San Wong, and Taiji Suzuki. Distributional Biases in Post-Training: A Markovian Analysis of Reasoning Trajectories. (ICML 2026 FoGen **Spotlight**) [[arXiv](https://arxiv.org/pdf/2511.07368)] [[code](https://github.com/DakeBU/Distribution-Bias-of-Post-training)]

- **Dake Bu**, Wei Huang, Andi Han, Atsushi Nitanda, Qingfu Zhang, Hau-San Wong, and Taiji Suzuki. Provable Sample Efficiency of Curriculum Post-Training for Transformer Reasoning. (ICML 2026) [[arXiv](https://arxiv.org/pdf/2511.07372)] [[code](https://github.com/DakeBU/Curriculum-Post-training)]

- **Dake Bu**, Wei Huang, Andi Han, Atsushi Nitanda, Qingfu Zhang, Hau-San Wong, and Taiji Suzuki. Provable In-Context Vector Arithmetic via Retrieving Task Concepts. The 42nd International Conference on Machine Learning (ICML 2025). [[arXiv](https://arxiv.org/abs/2508.09820)] [[code](https://github.com/DakeBU/In-Context-Vector-Arithmetic-via-Retrieving-Task-Concepts)]

- Bo Xue, **Dake Bu**, Ji Cheng, Yuanyu Wan, Qingfu Zhang. Multi-objective Linear Reinforcement Learning with Lexicographic Rewards. The 42nd International Conference on Machine Learning (ICML 2025). [[openreview](https://openreview.net/pdf?id=RTHTyTsRT3)]

- **Dake Bu**, Wei Huang, Andi Han, Atsushi Nitanda, Taiji Suzuki, Qingfu Zhang, Hau-San Wong. Provably Transformers Harness Multi-Concept Word Semantics for Efficient In-Context Learning. Advances in Neural Information Processing Systems 37 (NeurIPS 2024). [[arXiv](https://arxiv.org/abs/2411.02199)] [[code](https://github.com/DakeBU/Transformers-Harness-Multi-Concept-Word-Semantics-for-Efficient-In-Context-Learning)]

- **Dake Bu**, Wei Huang, Taiji Suzuki, Ji Cheng, Qingfu Zhang, Zhiqiang Xu, Hau-San Wong. Provably Neural Active Learning Succeeds via Prioritizing Perplexing Samples. (ICML 2024) [[arXiv](https://arxiv.org/abs/2406.03944)] [[code](https://github.com/DakeBU/Neural-Active-Learning-Succeeds-via-Prioritizing-Perplexing-Samples)]
